// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GroupMember struct {
	GroupID     pgtype.UUID        `json:"group_id"`
	IdentityID  pgtype.UUID        `json:"identity_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DisplayName string             `json:"display_name"`
	Phone       string             `json:"phone"`
	Title       *string            `json:"title"`
	IsPrimary   bool               `json:"is_primary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	Code        string             `json:"code"`
	Scope       string             `json:"scope"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Scope       string             `json:"scope"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Version     int32              `json:"version"`
}

type RoleAssignment struct {
	RoleID     pgtype.UUID        `json:"role_id"`
	IdentityID pgtype.UUID        `json:"identity_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID         pgtype.UUID        `json:"role_id"`
	PermissionCode string             `json:"permission_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID           pgtype.UUID        `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	ContactName  *string            `json:"contact_name"`
	ContactPhone *string            `json:"contact_phone"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TenantGroup struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	SortOrder   int32              `json:"sort_order"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
