// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*)
FROM tenants
WHERE (
    $1::text IS NULL
    OR name ILIKE '%' || $1::text || '%'
    OR code ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR status = $2::text
)
`

type CountTenantsParams struct {
	Search       *string `json:"search"`
	StatusFilter *string `json:"status_filter"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants, arg.Search, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id,
    code,
    name,
    status,
    contact_name,
    contact_phone,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, 'active'),
    $5,
    $6,
    COALESCE($7, '{}'::jsonb)
)
RETURNING
    id,
    code,
    name,
    status,
    contact_name,
    contact_phone,
    metadata,
    created_at,
    updated_at
`

type CreateTenantParams struct {
	ID           pgtype.UUID `json:"id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	Column4      interface{} `json:"column_4"`
	ContactName  *string     `json:"contact_name"`
	ContactPhone *string     `json:"contact_phone"`
	Column7      interface{} `json:"column_7"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Column4,
		arg.ContactName,
		arg.ContactPhone,
		arg.Column7,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT
    id,
    code,
    name,
    status,
    contact_name,
    contact_phone,
    metadata,
    created_at,
    updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT
    id,
    code,
    name,
    status,
    contact_name,
    contact_phone,
    metadata,
    created_at,
    updated_at
FROM tenants
WHERE (
    $1::text IS NULL
    OR name ILIKE '%' || $1::text || '%'
    OR code ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR status = $2::text
)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTenantsParams struct {
	Search       *string `json:"search"`
	StatusFilter *string `json:"status_filter"`
	OffsetValue  *int32  `json:"offset_value"`
	LimitValue   *int32  `json:"limit_value"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants,
		arg.Search,
		arg.StatusFilter,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.ContactName,
			&i.ContactPhone,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    code = $2,
    name = $3,
    status = $4,
    contact_name = $5,
    contact_phone = $6,
    metadata = COALESCE($7, metadata),
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    code,
    name,
    status,
    contact_name,
    contact_phone,
    metadata,
    created_at,
    updated_at
`

type UpdateTenantParams struct {
	ID           pgtype.UUID `json:"id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	Status       string      `json:"status"`
	ContactName  *string     `json:"contact_name"`
	ContactPhone *string     `json:"contact_phone"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.ContactName,
		arg.ContactPhone,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
